codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...95"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        if_no_uploads: error

ignore:
  - "tests/"
  - "setup.py"
  - "**/__init__.py"
  - "src/lancedb_mcp/__main__.py"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false